name: Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - name: Configure Git
      run: |
        git config --local user.email "srikanth.ganta13@gmail.com"
        git config --local user.name "grand-cat-unknown"
    - name: Run Deploy Script
      run: npm run deploy